matrix:
  include:
    - stage: unit test
      language: ruby
      services:
        - docker
      install:
        - touch .env
        - make build
      script: make test
    - stage: deploy
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: it86X+rPAF74DNqdZhBZVQ1DQEet9ah9sgbShZpGurvUrzk+UpdFDNDkErSJ/6uSkPRXD+jfhq4M1Cjh6R8SrselQHBILyaNV24YOxKOOfh+S0+8P93lH2s/74UDHxKDfzhz6xvfgRHSULdPAAmwwuIGWegCxnzMsCj65RY2sJpJz42lZL6BrCfi/rnuf7QU/n+z5z9EOPCphAkLvgZGbBenBmJ7diw041ShMh5PcebAYTPj0gK+f7QJma/06F2oKFaAWeCvWaum1uVnaK1W3FEZ2WPvOOHxzKTLMkjLIL6HwF6Si9tiGP0kI+6h2WLoVVG18RwolNJcuCeWdzUuYCj1upa/9/kn4CIwCw0007VwfANL2KSROevt7vjkL+ub4HCN6v6fk0OBYmoBHg3I6cmMkQk/n/nc4y7kIFJw5+vp8EsjB9LRobDhKSr3ORo6vPKbGGm+GS0H34OWCojGGsc1JXkA3K77MYuR4Na3XBmMDVKkebfqeqLLdVxIgJPFwn5MlITAA73PkuJ9LOb3TfFaOH5AzPEp+q5317PHDGoBDgWkaTnc/egDnV57AqjQwpwq3Y7P6HrRMpQx6i0T9PvAP2umD5By5K7IA0eTiEfhgDtvzMSBdL3BmXrzaWG+Olz3kPBHdBPyZh77VKtbPUPNvIgw4rrwszWAq7XYfjE=
        app: openk1tchen
