matrix:
  include:
    - stage: unit test
      language: ruby
      services:
        - docker
      install:
        - touch .env
        - make build
      script: make test
    - stage: deploy
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: bjGIB24IoycTi1unSikNBds7DCqc8mPtoh1CMV67YuSWRSbVcSsylHWKXHGWBrxrzTbJNvJwxBlX3JL9J+w6plZyMhMCkpZmBBuFLIhvnYK9XBRczbYtq5+FMbPH7kzTkYmS3HEra2ibqqnjEmsnfxeqBlkpirPO61bZlfRX/4KkxY3UiJ1iUrxbbxwLMfhi4gYfT9c43wMmLzxqe497YGKCFdZuWOfZK19p1nLb1Np/gzpUzL/NOuxob+m47Pu2HMJHZSwd0yk+1rm/+h+5GmSon2yI/2t/S12RKlQqCU1Aze4n+AN2gNRRC6MeVtbouPo0njVGW0Bl6IyoYH09DVsyqy5VlVffbMdxCqk9HU4jO4Y0jOcgH3ffdnIepCIG4EZw9URYWH24krefRH5enh47w6EKb8JrIjEaiz5iXLWaHycggzc9EhFARjpw+ipzfRi0KS64pBShTtY3tffLVIqWsivlzyLSkqSB9LejPuB0xcHu26BfJ9o2gmYQbCyvXs9jun2/9LIehTsxtgEjiZ50k1ttiTKQ2D5QH5GlOXLJg8FSXkz/pE3IEpkXh/z160U5Ua5NPeA1Q5ve4/L20neGdBNwMsX3+OnHmxBy4ii8GR2MbV+10V95gGsoGwu5i1jgAJaQFCRdJdFNiTtltv05ePCAl7+ewvVwgjGqlMw=
        app: openk1tchen
