matrix:
  include:
    - stage: unit test
      language: ruby
      services:
        - docker
      install:
        - touch .env
        - make build
      script: make test
    - stage: deploy
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: HFjwZ3hMDJp+Y9IG/er/f89q5meCBayihRkPdpi5G4PMkyh+G1DeTFIOVBwir5wMEks95/NBlHcIDdBG7YJnEyFacDxYSzhEjlknh1v2OjM7TL01+Em6CVVLMbgg2XXgSKLpFBzLQnuT9mERULnwqBpL2iAjPjTYgW1VKJgMVScPJnRcufPcNb0WPK7P7Igd1MXwOVJQP3yqkj8IeXyqO1DDj4kWIux7bXBfEkED9H/simad0Ss8k6bt4A8WjomhZsCX7n6TUeUa6JfAf1Yv+YAZ7vjtxlVLVieGW3329UfKMUfNJIQJsGu8UwHWHqpox4CMPonLdqOwtw+8llrkoQEYx75bFzZKR4m/yFr/sAh6eea+vLaPfvZE2IydymXNdivG73I5VxUjeLHYyk41u4kE/JehA51B4f8JsCJTGZ0GFVOZC3t9BY4JtDggtlzoOQCaB4hBqg+vlsJLAUI+SGxdM549i90s3tB8Xat+9rFbau+MoiO+mYRgH5TlfggAeHibaQy1aIabKiiCk45u4/0ME2I8DscmfOoY5HB2G6R2Ajw8/frQ3jFGhQlA0U4Mlz5LCZEi+nY06iBUVafgERVgAP61AOIp8Ke0mRO7GRr4Fna8Nv5DvKIoM8KnId1xMc6m8RuO6DxTMFdl+5ed9EZX7GHlNY5FxG7e/MGcU1c=
        app: project-boilerplate
