matrix:
  include:
    - stage: unit test
      language: ruby
      services:
        - docker
      install:
        - touch .env
        - make build
      script: make test
    - stage: deploy
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: evzHSVSlVfvPoo05BwAC19dtqXW5loVeMhHwjgzd0Lmc1LVDTTBQpWUBz7jVH/0eefPy26NJdWhfA36jJNavZWeoTMjI6pz8GqZZZE3UpxfaEhYRqULdmrE9/2BKwObXzmZcNod2uzoBJ9Lnsvlpgr8Pg66OY0gaWnM1mtRzo8BaIkH6rK1yNOrpPsVhZnUacKJQqPflTLDoAiA2eaRyEnqZTSxm7OqF4jHVhq6B1bSc/M/JRY81cTW9w/4M5MmoDxNpphTui4QZj0Y/i/eRqls4MCePj+cURrBJhzuL50UGyIDxkXzYICjlEgpmY7QYa7o09yUcR7LQ7GXJtZSXYFLikQxWeyIKdllul6wrwoTaHtoRa1qlCZsr4Cp+r1EUJ6+rK9gVK2zLImyFHsqmPZd1ZFQVXqX98fSy0vpzQQ5GoYNkE1+ZD45BdxWEmZl2NwjcxZg2PUPyzTMi9inVkVkvB1O+kROhw5EsiAveI8PWQHWj8pb37dzsEomrClDK1Oz4nGFWbt+gnUjt9w5QBRDNQ+Km4ouny1+UUMXvUVGTOoEYXtgbtgpEVJxGxA9K1otnWYGG+QoI/IEY9k8uSla7jiBx4nl86P8Lq5RBtUs3X2d0NeNlAvy28aDXqjckjPh4rVUSNz7rs8qX0wbfnpXj46dA37GXIhQISPpjhgM=
        app: openk1tchen
