matrix:
  include:
    - stage: unit test
      language: ruby
      services:
        - docker
      install:
        - touch .env
        - make build
      script: make test
    - stage: deploy
      if: branch = master
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: VMHRuxRZWup8HRgWCHXcE7YjVoiqDDCQFwOmJ+Y+8Il1iUgkA9GUGGeb2pHl8lNV2johe+J3XjlS76gpGHPgADssokT344l3JR2llWs/vyOKFWVNuOxj9LvzIby6MtUDigju1tpyvWM+TXfxhAU+xr+R6c7v6gxGGibmxPf2EITW90I63AXsIaXCHejbvPemEFqXw5mrWe8N59OhSC3tFJiAUlfeLFfWE4Kp9euxFRvgGXsk887rZ/et5Qm65/QBLRG8ApLHO2+nxAtkNrlcY299Wl/wyx4pYkKatJNrsktbcXjiQKP4qXynmYQBlK/GaLwbw1VKKaDVICDAWjM3jwLYRLKmtZhOt0IDErurxNlryS7Xb9CnwBqSnS1sP8TioIL7CHkeq9TEkgBvGDnpRrZu2uRvIakeHmda1fm15f5gFu02XfXHK7eF/ht1sH+LW9HkZYPBSUgE+QuGNvVfJFoBuSWw1LqXBEymu6jvtpAMkigeYWITPbWy1ctMfS1wVI3MdzBfsZCvZjydBm9IzQWzODkQZhgfzqQbQ0zuVeQ9tvrLgGKl0lx/pamaEzbABBNmA0Awld5JK/3G1W1Z69OLhc2ZWskv+7eFNmmNY/qCX+eclenKIT8IrHNZTrvpBV0Yh0cirC1K0fuIiKxlM7BS4/VtR6v1daNoHHLivnc=
        app: openk1tchen
